export enum STATUS_ORDER {
  PROCESSING = "PROCESSING",
  SHIPPING = "SHIPPING",
  RECEIVED = "RECEIVED",
  CANCELED = "CANCELED",
}

export interface StatusOrder {
  typeStatus:
    | STATUS_ORDER.PROCESSING
    | STATUS_ORDER.SHIPPING
    | STATUS_ORDER.RECEIVED
    | STATUS_ORDER.CANCELED;
}
